
@owner=mkol5222
@repo=gh-tf-policy
@path=policy/policy.json
@branch=plan

@policy={{$dotenv NEWPOLICY}}
@pat={{$dotenv PAT}}

###
# first we need sha1 of previous policy
#
# @name getPolicyInfo
GET https://api.github.com/repos/{{owner}}/{{repo}}/contents/{{path}}?ref={{branch}}
authorization: token {{pat}}



###
# @name updatePolicy
PUT https://api.github.com/repos/{{owner}}/{{repo}}/contents/{{path}}
authorization: token {{pat}}
Content-Type: application/json

{
  "message": "api: updating policy.json",
  "content": "{{policy}}",
  "branch": "{{branch}}",
  "sha": "{{getPolicyInfo.response.body.sha}}"
}

###
# access artifacts like terraform plan and state
#
GET https://api.github.com/repos/{{owner}}/{{repo}}/actions/artifacts
authorization: Bearer {{pat}}
Accept: application/vnd.github+json
X-GitHub-Api-Version: 2022-11-28

###
# list of workflow runs
# on branch and with status completed
# and created today
# @name getRuns
@today={{$localDatetime 'YYYY-MM-DD'}}
GET https://api.github.com/repos/{{owner}}/{{repo}}/actions/runs?branch={{branch}}&status=completed&created={{today}}
authorization: Bearer {{pat}}
Accept: application/vnd.github+json
X-GitHub-Api-Version: 2022-11-28

###
# access workflow run logs
#
# @name getLogs

# NOTICE: this one returns redirect to file, so use Rest Clint: Copy as cURL and add -L -o logs.zip to download logs
#    consider first cd to temp folder:      cd $(mktemp -d)

@runId={{getRuns.response.body.workflow_runs.0.id}}
@logsUrl={{getRuns.response.body.workflow_runs.0.logs_url}}
# https://api.github.com/repos/${owner}/${repo}/actions/runs/${runId}/logs

GET {{logsUrl}}
authorization: Bearer {{pat}}


###
# list all workflows - e.g. to run one of them later
# @name getWorkflows

GET https://api.github.com/repos/{{owner}}/{{repo}}/actions/workflows
authorization: Bearer {{pat}}

###
# run workflow
# requires PAT with actions:write
@workflowId={{getWorkflows.response.body.workflows.0.id}}
@workflowName={{getWorkflows.response.body.workflows.0.name}}

# notice request body input apply false/true

POST https://api.github.com/repos/{{owner}}/{{repo}}/actions/workflows/{{workflowId}}/dispatches
authorization: Bearer {{pat}}
Content-Type: application/json

{
  "ref": "{{branch}}",
  "inputs": {
    "apply": true
  }
}

