# This is a basic workflow to help you get started with Actions

name: TF

on:
#   push:
#     branches: [ "plan" ]
    
  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Load TF state
        uses: actions/download-artifact@v3
        with:
          name: tfstate
          path: terraform.tfstate
        continue-on-error: true

      - name: Load TF plan
        uses: actions/download-artifact@v3
        with:
          name: tfplan
          path: plan.tfplan

      - name: apply
        run: |
          cat ./policy/policy.json | jq
          sha1sum ./policy/policy.json
          terraform init
          terraform apply -auto-approve plan.tfplan
      
    #   - name: Save TF plan
    #     uses: actions/upload-artifact@v3
    #     with:
    #       name: tfplan
    #       path: plan.tfplan

      - name: Save TF state
        uses: actions/upload-artifact@v3
        with:
          name: tfstate
          path: terraform.tfstate
      
          
